### ISSUE TITLE
STATIC hostnames in dnsmasq?

### ISSUE THREAD

**Issue by walthowd** [tumescentrubor/Orbi-s-Non-Sufficit#1]
Should these static hostname be appended to /etc/hosts?

```
STATIC="127.0.0.1 localhost
192.168.86.1 orbi orbi.gyre
192.168.86.1 www.routerlogin.net
192.168.86.99 satellite satellite.gyre
192.168.86.3 albedo
192.168.86.4 deluge
192.168.86.30 radiology www"
```

https://github.com/tumescentrubor/Orbi-s-Non-Sufficit/blob/master/modules/fix_dns/init/fix_dns.sh

**Comment by tumescentrubor** [comment]
Hi!
Those are names of hosts on my local network, most of them have static IP assignments, that I want dnsmasq to resolve for me. You can/should change them to to any static assignments you want for your own LAN. At the minimum, I think you'd want to leave the localhost assignment, and change the IP address for your Orbi to whatever it should be for you.
I think I should put a note in there to make this clear. Thanks for reminding me.
